failfast: false
repos:
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id:  black
    name: black (via python 3)
    language_version: python3.9
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.8.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0  # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
    args: [--unsafe]
  - id: check-toml
  - id: check-json
  - id: end-of-file-fixer
  - id: check-ast
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2  # Use the sha / tag you want to point at
  hooks:
  - id: flake8
    args: # arguments to configure flake8
      # making isort line length compatible with black
      - "--max-line-length=88"
    additional_dependencies:
      - flake8-black>=0.1.1
    language_version: python3.9
